sudo: required
language: python

services:
  - docker

script:
  - docker build --build-arg GIT_COMMIT_SHA="${TRAVIS_COMMIT}" -t webapp .

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password=stdin
  - docker tag webapp "${DOCKER_USERNAME}/webapp:${TRAVIS_COMMIT}" "${DOCKER_USERNAME}/webapp:latest"

deploy:
  provider: script
  script: docker push "${DOCKER_USERNAME}/webapp:${TRAVIS_COMMIT}" && docker push "${DOCKER_USERNAME}/webapp:latest"
  on:
    branch: master